version: '3'

services: 
    db:
        image: mariadb:10.4
        environment: 
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=app
        ports: 
            - 3307:3306
        volumes: 
            - ./db_data:/etc/mysql/conf.d

    app:
        image: pizelli/webserver:1.1
        volumes: 
            - ./:/var/www/html
        ports: 
            - 8080:80
        links: 
            - db
        depends_on: 
            - db
        tty: true
        